services:
  nginx-gateway:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile.prod
    container_name: todo-nginx-prod
    ports:
      - "80:80"
    depends_on:
      - backend-api
    networks:
      - todo_network
    restart: always

  backend-api:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile.prod
    container_name: todo-backend-prod
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_KEY: base64:ckRuwUBXKn4X17CeFFWCwmKOnbb0/ynuhS7LQebsoT4=
      JWT_SECRET: SvnCbM7pzx36tytyTa6UzV20x9g48TRSuKnayCO40Ck5BYHoTWR53y7dMLyruADH
      JWT_ALGO: HS256
      DB_CONNECTION: pgsql
      DB_HOST: database
      DB_PORT: 5432
      DB_DATABASE: todo_app
      DB_USERNAME: todo_user
      DB_PASSWORD: secret
      REDIS_HOST: redis
      CACHE_STORE: database
      SESSION_DRIVER: database
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - todo_network
    restart: always

  database:
    image: postgres:16-alpine
    container_name: todo-database-prod
    environment:
      POSTGRES_DB: todo_app
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: secret
    volumes:
      - todo_pgdata_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo_user -d todo_app"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - todo_network
    restart: always

  redis:
    image: redis:7-alpine
    container_name: todo-redis-prod
    networks:
      - todo_network
    restart: always

volumes:
  todo_pgdata_prod:
    driver: local

networks:
  todo_network:
    driver: bridge
